### ISSUE TITLE
Feature already available

### ISSUE THREAD

**Issue by euh2** [kankaristo/gnome-shell-extension-top-bar-middle-click-to-lower#1]
The Gnome Tweak Tool has this setting under `Topbar`.

**Comment by kankaristo** [comment]
What version of Gnome / Gnome Tweak Tool are you using?

All I have under "Top Bar" are:
- Show application menu
- Show date
- Show seconds
- Show week numbers

**Comment by euh2** [comment]
Ah, it is at `Windows` `Action on Title bar`. There you can choose an acton on `Middle Click`.

**Comment by kankaristo** [comment]
Yeah, I have that turned on too, this extension is a complement to that.

This extension makes "middle click to lower" also work on maximised windows, in case you're using [Maximus Two](https://extensions.gnome.org/extension/844/maximus-two/) (or some similar extension), which hides the title bar for maximised windows. Instead of middle clicking on the title bar (which is hidden), you middle click on the top bar, and it lowers the window.

I'll close this for now, please reopen/comment if I misunderstood.

**Comment by kankaristo** [comment]
P.S.
Only problem is, Maximus, Maximus Two and Maximus NG all seem to be no longer actively developed. I think I'm using Maximus NG, which seems to work still.
